# Numpy

In [ ]:
#numpy - numerical python

In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6,7])

array([2, 3, 4, 5, 6, 7])

In [4]:
type(np.array([2,3,4,5,6,7]))

numpy.ndarray

In [6]:
np.array([[2,3,4,5],[6,7,8,9]])

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [7]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [8]:
l = [[1,2,3,4],[2,3,4,5]]

In [10]:
l[0][0]

1

In [16]:
a = np.array([1,2,3,4], ndmin = 3)
a

array([[[1, 2, 3, 4]]])

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.ndim

2

In [23]:
#objective is to show 3d array
np.random.randint(1,10,(4,4))


array([[6, 4, 3, 2],
       [5, 6, 5, 6],
       [6, 9, 6, 6],
       [2, 5, 3, 1]])

In [24]:
np.random.randint(1,10,(4,4,2))

array([[[6, 7],
        [6, 3],
        [8, 2],
        [5, 6]],

       [[2, 7],
        [7, 6],
        [5, 3],
        [3, 9]],

       [[6, 7],
        [4, 7],
        [5, 6],
        [7, 4]],

       [[9, 9],
        [7, 3],
        [1, 7],
        [6, 9]]])