# Numpy Numerical Python

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6,7]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
l1= [2,3,4,5,6,"numpy",34.56, True]
a1= np.array(l1)
a1

array(['2', '3', '4', '5', '6', 'numpy', '34.56', 'True'], dtype='<U11')

In [12]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3=np.array([[[1,2,3],[4,5,6],[6,7,8]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [15]:
a1.ndim
#ndim is function to describe the dimension of function, used for data manipulation operations

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
a1.size

8

In [19]:
a2.size

6

In [20]:
a3.size

9

In [21]:
a1.shape

(8,)

In [22]:
a2.shape

(2, 3)

In [23]:
a3.shape

(1, 3, 3)

In [34]:
np.random.randint(2,50)
#generate a random int data between 2 to 50

43

In [35]:
np.random.randint(2,50,(3,4))
#generate a random int data between 2 to 50 with dimenion of 3*4

array([[47, 27,  8, 34],
       [30, 27, 20, 18],
       [ 4, 25, 42, 25]])

In [41]:
np.random.randint(2,50,(2,3,4))

array([[[38, 17,  9, 11],
        [31, 20, 37, 10],
        [14, 21,  2, 28]],

       [[ 3, 37, 30, 42],
        [43, 31, 21, 44],
        [ 4,  4,  7, 41]]])

In [43]:
np.random.rand(5,4)

array([[0.91073381, 0.03612542, 0.45723324, 0.91129039],
       [0.500624  , 0.31276146, 0.93504955, 0.70099554],
       [0.02745969, 0.79555332, 0.83466941, 0.33950062],
       [0.34028857, 0.01337989, 0.99597414, 0.36415729],
       [0.23619714, 0.35864728, 0.06102047, 0.75403001]])

In [48]:
a4 = np.random.randn(4,4)
a4
#normal distribution - Mean (average) is approx 0: take any column and calculate 

array([[ 0.00436264, -2.43728115, -1.52724355, -0.17934436],
       [-1.76952564,  1.76500857,  0.4400601 , -1.18466013],
       [-0.22652644,  0.1016454 , -0.45106478, -0.22846152],
       [ 0.84845779, -1.68123203, -0.30428638,  0.10110112]])

In [53]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [54]:
a4.reshape(2,8)
#need to define similar data storing like for 4x4 is having 16 data so, either 2x8 or 8x2 

array([[ 0.00436264, -2.43728115, -1.52724355, -0.17934436, -1.76952564,
         1.76500857,  0.4400601 , -1.18466013],
       [-0.22652644,  0.1016454 , -0.45106478, -0.22846152,  0.84845779,
        -1.68123203, -0.30428638,  0.10110112]])

In [55]:
a4.reshape(2,-1)
#whenever you give a negative number then numpy just decide and reshape it automatically

array([[ 0.00436264, -2.43728115, -1.52724355, -0.17934436, -1.76952564,
         1.76500857,  0.4400601 , -1.18466013],
       [-0.22652644,  0.1016454 , -0.45106478, -0.22846152,  0.84845779,
        -1.68123203, -0.30428638,  0.10110112]])

In [57]:
a4.reshape(2,-13333)

array([[ 0.00436264, -2.43728115, -1.52724355, -0.17934436, -1.76952564,
         1.76500857,  0.4400601 , -1.18466013],
       [-0.22652644,  0.1016454 , -0.45106478, -0.22846152,  0.84845779,
        -1.68123203, -0.30428638,  0.10110112]])

In [59]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[ 0.00436264, -2.43728115, -1.52724355,
                -0.17934436],
               [-1.76952564,  1.76500857,  0.4400601 ,
                -1.18466013]],

              [[-0.22652644,  0.1016454 , -0.45106478,
                -0.22846152],
               [ 0.84845779, -1.68123203, -0.30428638,
                 0.10110112]]]]]]]]]])

In [64]:
a1



array(['2', '3', '4', '5', '6', 'numpy', '34.56', 'True'], dtype='<U11')

In [65]:
a1[0]

'2'

In [66]:
a1[2:6]

array(['4', '5', '6', 'numpy'], dtype='<U11')

In [67]:
a1[2:6:2]
#slicing operation from 2 position to  6 position (excluding the upper bound)  with the jump of 2

array(['4', '6'], dtype='<U11')

In [68]:
a1[::-1]
#reverse the entire array

array(['True', '34.56', 'numpy', '6', '5', '4', '3', '2'], dtype='<U11')

In [69]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a2[0]

array([1, 2, 3])

In [73]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [74]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [75]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [77]:
a5=np.random.randint(2,90,(6,5))
a5

array([[79,  7, 15, 79, 67],
       [48,  3, 33, 30, 72],
       [84,  8, 26, 31, 11],
       [81, 70,  5, 65, 23],
       [77, 19, 48, 61, 31],
       [78, 79, 27, 15, 31]])

In [78]:
a5[a5>40]

array([79, 79, 67, 48, 72, 84, 81, 70, 65, 77, 48, 61, 78, 79])

In [80]:
a5[0,1]=100
a5
#to change the value of [0,1] index as 100

array([[ 79, 100,  15,  79,  67],
       [ 48,   3,  33,  30,  72],
       [ 84,   8,  26,  31,  11],
       [ 81,  70,   5,  65,  23],
       [ 77,  19,  48,  61,  31],
       [ 78,  79,  27,  15,  31]])

In [85]:
a6 = np.random.randint(0,3,(3,3))
a6

array([[1, 2, 0],
       [2, 2, 2],
       [0, 2, 2]])

In [84]:
a7 = np.random.randint(0,3,(3,3))
a7

array([[1, 1, 2],
       [1, 1, 2],
       [0, 2, 1]])

In [86]:
a6*a7
# it is element wise multiplication

array([[1, 2, 0],
       [2, 2, 4],
       [0, 4, 2]])

In [87]:
a6@a7
#for matrix multiplication numpy provide "@" symbol

array([[ 3,  3,  6],
       [ 4,  8, 10],
       [ 2,  6,  6]])

In [89]:
a6

array([[1, 2, 0],
       [2, 2, 2],
       [0, 2, 2]])

In [90]:
a6+100

array([[101, 102, 100],
       [102, 102, 102],
       [100, 102, 102]])

In [92]:
a6/0

C:\Users\Rajan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Rajan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, nan],
       [inf, inf, inf],
       [nan, inf, inf]])

In [93]:
a6

array([[1, 2, 0],
       [2, 2, 2],
       [0, 2, 2]])

In [94]:
a6**3 #power operation

array([[1, 8, 0],
       [8, 8, 8],
       [0, 8, 8]], dtype=int32)

In [95]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
a9 =np.ones((4,5))
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

This is known as Bradcasting operation

In [101]:
a9 + np.array([1,2,3,4,5])
# row wise it is trying to add it and adding element should be same as columns

# This is known as Bradcasting operation

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [102]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [111]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [112]:
a5

array([[ 79, 100,  15,  79,  67],
       [ 48,   3,  33,  30,  72],
       [ 84,   8,  26,  31,  11],
       [ 81,  70,   5,  65,  23],
       [ 77,  19,  48,  61,  31],
       [ 78,  79,  27,  15,  31]])

In [113]:
#sqrt for each element
np.sqrt(a5)

array([[ 8.88819442, 10.        ,  3.87298335,  8.88819442,  8.18535277],
       [ 6.92820323,  1.73205081,  5.74456265,  5.47722558,  8.48528137],
       [ 9.16515139,  2.82842712,  5.09901951,  5.56776436,  3.31662479],
       [ 9.        ,  8.36660027,  2.23606798,  8.06225775,  4.79583152],
       [ 8.77496439,  4.35889894,  6.92820323,  7.81024968,  5.56776436],
       [ 8.83176087,  8.88819442,  5.19615242,  3.87298335,  5.56776436]])

In [114]:
np.exp(a5)
#Exponential of a5

array([[2.03828107e+34, 2.68811714e+43, 3.26901737e+06, 2.03828107e+34,
        1.25236317e+29],
       [7.01673591e+20, 2.00855369e+01, 2.14643580e+14, 1.06864746e+13,
        1.85867175e+31],
       [3.02507732e+36, 2.98095799e+03, 1.95729609e+11, 2.90488497e+13,
        5.98741417e+04],
       [1.50609731e+35, 2.51543867e+30, 1.48413159e+02, 1.69488924e+28,
        9.74480345e+09],
       [2.75851345e+33, 1.78482301e+08, 7.01673591e+20, 3.10429794e+26,
        2.90488497e+13],
       [7.49841700e+33, 2.03828107e+34, 5.32048241e+11, 3.26901737e+06,
        2.90488497e+13]])

In [115]:
np.log10(a5)

array([[1.89762709, 2.        , 1.17609126, 1.89762709, 1.8260748 ],
       [1.68124124, 0.47712125, 1.51851394, 1.47712125, 1.8573325 ],
       [1.92427929, 0.90308999, 1.41497335, 1.49136169, 1.04139269],
       [1.90848502, 1.84509804, 0.69897   , 1.81291336, 1.36172784],
       [1.88649073, 1.2787536 , 1.68124124, 1.78532984, 1.49136169],
       [1.8920946 , 1.89762709, 1.43136376, 1.17609126, 1.49136169]])

In [116]:
range(0,19)
#generate numbers from 0 to 19 excluding 19

range(0, 19)

In [117]:
list(range(0,9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [119]:
list(range(0,9,2))

[0, 2, 4, 6, 8]

In [120]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.arange(1,10,2.9)
#In numpy floting jump point is allowed whereas in Range function floating point number are not allowed
#this is the only difference in Range and numpy arange function


array([1. , 3.9, 6.8, 9.7])

In [123]:
np.linspace(2,3, num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [124]:
np.linspace(2,3, num=50, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [125]:
np.logspace(2,4,num=4, base =10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [126]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])